/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
 import javax.swing.JOptionPane;
 import javax.swing.table.*;
/**
 *
 * @author BLASTER's PC
 */
public class ShowRecords extends javax.swing.JFrame {

    /**
     * Creates new form ShowRecords
     * 
     */
    public ShowRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TB = new javax.swing.JTable();
        srb1 = new javax.swing.JButton();
        srb2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TB.setBackground(new java.awt.Color(204, 255, 204));
        TB.setForeground(new java.awt.Color(255, 0, 0));
        TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "AGE", "PHONE NO.", "ACC NO,", "ACC TYPE", "ADDRESS", "AMOUNT", "AADHAR NO."
            }
        ));
        jScrollPane1.setViewportView(TB);

        srb1.setText("Show Data");
        srb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srb1ActionPerformed(evt);
            }
        });

        srb2.setText("Back To Main Menu");
        srb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(srb1)
                        .addGap(154, 154, 154)
                        .addComponent(srb2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srb1)
                    .addComponent(srb2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srb2ActionPerformed
        
       
            MainMenu1 obj = new MainMenu1();
            obj.setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_srb2ActionPerformed

    private void srb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srb1ActionPerformed
        
        DefaultTableModel model=(DefaultTableModel)TB.getModel();
       
try
{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bankingdatabase","root","root");
Statement S=con.createStatement();
ResultSet Rs=S.executeQuery("Select * from accountdatabase ORDER BY 'Account No';");
while(Rs.next())
{
    String N=Rs.getString("Name");
int A=Rs.getInt("Age");
int P=Rs.getInt("PhoneNo");
int AC=Rs.getInt("AccountNo");
String AT=Rs.getString("AccountType");
String AD=Rs.getString("Address");
float AM=Rs.getFloat("Amount");
long AN=Rs.getInt("AadharNo");
model.addRow(new Object[]{N,A,P,AC,AT,AD,AM,AN});

}      
Rs.close();
S.close();
con.close();

}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);

        }
        
    }//GEN-LAST:event_srb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShowRecords().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton srb1;
    private javax.swing.JButton srb2;
    // End of variables declaration//GEN-END:variables
}
